### ISSUE TITLE
[keyring-controller] `addAccountWithoutUpdate` now updates the `PreferencesController` state

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#3848] opened 2024-01-25 16:42 UTC
The `KeyringController` method `addAccountWithoutUpdate` no longer works; it does add the account, but not without updating state to include thew new account.

This was broken in `@metamask/preferences-controller@7.0.0`

**Comment by Gudahtt** [comment] 2024-01-25 16:44
Maybe we can remove this method instead of fixing it. Will investigate if it's still needed.

It was added originally for this mobile feature: https://github.com/MetaMask/metamask-mobile/pull/1879
But I'm not sure what negative impact temporarily adding the account has; maybe it's OK to add it then remove it during the import process.

Alternatively, we could update the keyring API to add a method that returns the next account address without adding it. That would solve the problem as well.

**Comment by mikesposito** [comment] 2024-01-25 17:42
> Alternatively, we could update the keyring API to add a method that returns the next account address without adding it. That would solve the problem as well.

@Gudahtt This could be similar to what also hardware keyrings currently do with `getPreviousPage`, `getNextPage`, `getFirstPage`: they provide a way to seek for accounts before adding them. 

Perhaps we could think of a way to standardise that and add it to the general Keyring API? It might be a way to fix this issue while also making the Hardware keyrings easier to use, and a bit more aligned with how other keyrings work

**Comment by Gudahtt** [comment] 2024-01-25 17:44
Good point, yes it's exactly like that

**Comment by desi** [comment] 2024-02-01 16:46
@Gudahtt has offered to test on mobile to determine if the method is even needed.

**Comment by mikesposito** [comment] 2024-04-19 10:24
@Gudahtt Regardless of the test I think we can close this and simply remove the method: `addNewAccountWithoutUpdate` never worked as intended since calling `persistAllKeyrings` also updates the controller state along with the vault

**Comment by Gudahtt** [comment] 2024-04-23 13:23
This method was intended just to avoid updating `PreferencesController` state, not all state. The `KeyringController` state update was not intended to be prevented. I do think it had worked prior to v7 of the `PreferencesController`.

**Comment by mcmire** [comment] 2024-06-26 18:04
@mikesposito @Gudahtt Just checking, is this ticket still relevant?

**Comment by desi** [comment] 2024-09-19 15:15
We believe this isn't an issue but we should verify and close.

**Comment by mikesposito** [comment] 2024-09-24 10:45
I opened a PR on mobile to stop using this method in favor of a more efficient solution: https://github.com/MetaMask/metamask-mobile/pull/11409

We can proceed to remove the method from `KeyringController` altogether

**Closed** 2024-11-27 15:39 UTC
Labels: bug, team-wallet-framework
