### ISSUE TITLE
KeyringController:removeAccount deleted HD Key Tree keyring from state

### ISSUE THREAD

**Issue by jpuri** [MetaMask/core#801] opened 2022-04-25 10:03 UTC
If there is only HD Key Tree keyring with 1 account and removeAccount is called passing that account it deletes keyring object also from state.

**Comment by Gudahtt** [comment] 2023-01-24 14:25
To some extent, this is intended behavior (`removeAccount` is meant to ensure empty keyrings are removed). But in this case we shouldn't be allowing this account to be removed, since we need at least one account for the wallet to function (for now anyway).

**Comment by mikesposito** [comment] 2024-05-16 15:40
This issue has been fixed by https://github.com/MetaMask/core/pull/4168

**Closed by mikesposito** 2024-05-16 15:40 UTC
Labels: bug, team-shared-libraries
